image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install tools
    init: > 
      rustup target add wasm32-unknown-unknown &&
      npm i -g near-cli &&
      gp sync-done installs
    command: echo "Installed all tools"

  - name: Install all npm packaged
    init: >
      npm i

  - name: Run Test
    init: >
      gp sync-await installs &&
      cargo test -- --nocapture &&
      gp sync-done test
    command: echo "Ran all test"
  
  - name: Build
    init: >
      gp sync-await test &&
      cargo build --target wasm32-unknown-unknown --release
    command: echo "Built the wasm files"
